  single_input,
  file_input,
  eval_input,
  decorator,
  decorators,
  decorated,
  funcdef,
  parameters,
  typedargslist,
  tfpdef,
  varargslist,
  vfpdef,
  stmt,
  simple_stmt,
  small_stmt,
  expr_stmt,
  testlist_star_expr,
  augassign,
  del_stmt,
  pass_stmt,
  flow_stmt,
  break_stmt,
  continue_stmt,
  return_stmt,
  yield_stmt,
  raise_stmt,
  import_stmt,
  import_name,
  import_from,
  import_as_name,
  dotted_as_name,
  import_as_names,
  dotted_as_names,
  dotted_name,
  global_stmt,
  nonlocal_stmt,
  assert_stmt,
  compound_stmt,
  if_stmt,
  while_stmt,
  for_stmt,
  with_stmt,
  with_item,
  except_clause,
  suite,
  test,
  test_nocond,
  lambdef,
  lambdef_nocond,
  or_test,
  and_test,
  not_test,
  comparison,
  comp_op,
  star_expr,
  expr,
  xor_expr,
  and_expr,
  shift_expr,
  arith_expri,
  term,
  factor,
  power,
  atom,
  testlist_comp,
  trailer,
  subscriptlist,
  subscript,
  sliceop,
  exprlist,
  testlist,
  dictorsetmaker,
  arglist,
  argument,
  comp_iter,
  comp_for,
  comp_if,
  yield_expr,
  yield_arg,

  // MISC
  sq,             // '
  NEWLINE,        // \n
  sqbrop,         // [
  sqbrcl,         // ]
  parenop,        // (
  parencl,        // )
  rex_or,         // |
  rex_star,       // *
  ENDMARKER,      // EOF
  rex_plus,       // +
  NAME,
